# Changes here will be overwritten by Copier
_commit: v0.4.1
_src_path: https://github.com/linkml/linkml-project-copier
add_example: false
copyright_year: '2025'
email: robert.carroll@vumc.org
full_name: Robert Carroll
gh_action_docs_preview: true
gh_action_pypi: false
github_org: include-dcc
license: MIT
project_description: Internal Access model for the INCLUDE DCC.
project_name: include-access-model
project_slug: include_access_model

